//Declaramos las variables "Globales" para el juego.
var numFicha = 0;
var colorDrag;
var xOr,yOr;
var tauler;
var minim;
var feliz;
var busca;
var porCas;
var porVerda;
var casTotal = 100;
var casPlenes;
var ficVerdes;
var ficBlaves;
var click;
var turno;
var infelices;
var dir;
var guanyat;
var juego;